[tools]
node = "24"
rust = "1.93.0"
java = "openjdk-25.0.2"
"aqua:evilmartians/lefthook" = '2'
"aqua:pnpm/pnpm" = '10'

[tasks.default]
run = "pnpm run dev"

[tasks.build]
run = "pnpm run build"

[tasks.update_dependencies]
run = ['pnpm dlx npm-check-updates -u', 'pnpm install']
